services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 428842
      POSTGRES_DB: metroApiDb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  webapi:
    build: ../../metroBackend
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=metroApiDb;Username=postgres;Password=428842
    ports:
      - "5000:80"

volumes:
  pgdata:
